baseURL: https://superb-marshmallow-0da4ad.netlify.app
languageCode: en-us
title: Example Blog
theme: elephants
params:
  sitename: Iman's Recipes

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$

markup:
  goldmark:
    renderer:
      unsafe: true

