baseURL: https://imansrecipes.com
languageCode: en-us
title: Iman's Recipes
theme: elephants
params:
  sitename: Iman's Recipes

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
  - \.prettierrc.json

markup:
  goldmark:
    renderer:
      unsafe: true
